// Code generated by the QED Extension catalog generator; DO NOT EDIT.
// Source: extensions.lock

package extensionregistry

import (
	extension0 "example.com/downstream/greeting"
	extensionmanifest "github.com/qed-runtime/qed/extension/manifest"
	selfexec "github.com/qed-runtime/qed/extension/selfexec"
)

// Catalog contains the self-exec Extensions selected by extensions.lock
var Catalog = selfexec.MustNewCatalog([]selfexec.Definition{
	{
		Manifest: extensionmanifest.Declaration{
			ID:              "downstream.greeting",
			Version:         "1.0.0",
			ProtocolVersion: 2,
			Capabilities:    []string{"downstream.read"},
		},
		ServerOptions: extension0.ServerOptions,
	},
})
