// Code generated by the QED Extension catalog generator; DO NOT EDIT.
// Source: extensions.lock

package extensionregistry

import (
	extensionmanifest "github.com/qed-runtime/qed/extension/manifest"
	selfexec "github.com/qed-runtime/qed/extension/selfexec"
	extension0 "github.com/qed-runtime/qed/extensions/git"
	extension1 "github.com/qed-runtime/qed/extensions/process"
	extension2 "github.com/qed-runtime/qed/extensions/workspace"
)

// Catalog contains the self-exec Extensions selected by extensions.lock
var Catalog = selfexec.MustNewCatalog([]selfexec.Definition{
	{
		Manifest: extensionmanifest.Declaration{
			ID:              "qed.git",
			Version:         "0.1.0",
			ProtocolVersion: 2,
			Capabilities:    []string{"git.read"},
		},
		ServerOptions: extension0.ServerOptions,
	},
	{
		Manifest: extensionmanifest.Declaration{
			ID:              "qed.process",
			Version:         "0.1.0",
			ProtocolVersion: 2,
			Capabilities:    []string{"process.execute"},
		},
		ServerOptions: extension1.ServerOptions,
	},
	{
		Manifest: extensionmanifest.Declaration{
			ID:              "qed.workspace",
			Version:         "0.1.0",
			ProtocolVersion: 2,
			Capabilities:    []string{"filesystem.read", "filesystem.write"},
		},
		ServerOptions: extension2.ServerOptions,
	},
})
