// Code generated by qed extension generate; DO NOT EDIT.
// Source: extensions.lock

package extensionregistry

import (
	extensionmanifest "github.com/qed-runtime/qed/extension/manifest"
	extension0 "github.com/qed-runtime/qed/extensions/git"
	extension1 "github.com/qed-runtime/qed/extensions/process"
	extension2 "github.com/qed-runtime/qed/extensions/workspace"
)

var generatedCatalog = map[string]catalogEntry{
	"qed.git": {
		declaration: extensionmanifest.Declaration{
			ID:              "qed.git",
			Version:         "0.1.0",
			ProtocolVersion: 1,
			Capabilities:    []string{"git.read"},
		},
		serverOptions: extension0.ServerOptions,
	},
	"qed.process": {
		declaration: extensionmanifest.Declaration{
			ID:              "qed.process",
			Version:         "0.1.0",
			ProtocolVersion: 1,
			Capabilities:    []string{"process.execute"},
		},
		serverOptions: extension1.ServerOptions,
	},
	"qed.workspace": {
		declaration: extensionmanifest.Declaration{
			ID:              "qed.workspace",
			Version:         "0.1.0",
			ProtocolVersion: 1,
			Capabilities:    []string{"filesystem.read", "filesystem.write"},
		},
		serverOptions: extension2.ServerOptions,
	},
}
