// Package agent provides the embeddable execution primitives for QED Runtime
package agent

import (
	"context"
	"encoding/json"
	"time"
)

// Role identifies the author or purpose of a message
type Role string

// Message roles supported by the minimal runtime
const (
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleTool      Role = "tool"
)

// Message is the provider-neutral message representation used by a Run
type Message struct {
	// Role identifies the author or purpose of the message
	Role Role `json:"role"`
	// Text contains user, assistant, or Tool output text
	Text string `json:"text,omitempty"`
	// ToolCallID correlates a Tool result message with its request
	ToolCallID string `json:"tool_call_id,omitempty"`
	// ToolName identifies the Tool that produced a result message
	ToolName string `json:"tool_name,omitempty"`
	// ToolIsError reports whether a Tool result represents an execution failure
	ToolIsError bool `json:"tool_is_error,omitempty"`
	// ToolCalls contains Tool requests produced by an assistant message
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	// StopReason contains the provider-neutral reason generation stopped
	StopReason StopReason `json:"stop_reason,omitempty"`
	// RawStopReason preserves the Provider-specific stop reason when available
	RawStopReason string `json:"raw_stop_reason,omitempty"`
	// Usage contains token counts reported for this assistant message
	Usage *Usage `json:"usage,omitempty"`
	// ResponseID identifies the Provider response when available
	ResponseID string `json:"response_id,omitempty"`
	// Model identifies the model reported by the Provider when available
	Model string `json:"model,omitempty"`
	// ProviderState carries opaque in-memory continuation data between calls
	//
	// ProviderState is not serialized. Callers must treat it as opaque and only
	// pass it back to a Provider with the same name
	ProviderState *ProviderState `json:"-"`
}

// StopReason identifies why a Provider stopped generating a message
type StopReason string

// Provider-neutral stop reasons
const (
	StopReasonEndTurn       StopReason = "end_turn"
	StopReasonToolUse       StopReason = "tool_use"
	StopReasonMaxTokens     StopReason = "max_tokens"
	StopReasonRefusal       StopReason = "refusal"
	StopReasonContentFilter StopReason = "content_filter"
	StopReasonUnknown       StopReason = "unknown"
)

// Usage contains Provider-reported token counts
type Usage struct {
	// InputTokens is the total number of tokens consumed by model input
	//
	// When InputTokenDetailsReported is true, InputTokens equals the sum of
	// UncachedInputTokens, CacheReadInputTokens, and CacheWriteInputTokens
	InputTokens int64 `json:"input_tokens"`
	// OutputTokens is the number of tokens generated by the model
	OutputTokens int64 `json:"output_tokens"`
	// TotalTokens is the Provider-reported or calculated total token count
	TotalTokens int64 `json:"total_tokens"`
	// InputTokenDetailsReported indicates that all input cache categories were reported
	InputTokenDetailsReported bool `json:"input_token_details_reported,omitempty"`
	// UncachedInputTokens is input that was neither read from nor written to cache
	UncachedInputTokens int64 `json:"uncached_input_tokens,omitempty"`
	// CacheReadInputTokens is input served from a Provider prompt cache
	CacheReadInputTokens int64 `json:"cache_read_input_tokens,omitempty"`
	// CacheWriteInputTokens is input written to a Provider prompt cache
	CacheWriteInputTokens int64 `json:"cache_write_input_tokens,omitempty"`
	// CostMicros contains Provider-reported cost in millionths of the configured currency
	//
	// Zero means that the Provider did not report cost
	CostMicros int64 `json:"cost_micros,omitempty"`
}

// ProviderState contains opaque continuation data owned by one Provider
type ProviderState struct {
	// Provider is the exact Provider name that owns Data
	Provider string
	// Data contains Provider-specific continuation state
	Data json.RawMessage
}

// ToolCall requests one execution of a registered Tool
type ToolCall struct {
	// ID correlates the request with its result and is generated when omitted
	ID string `json:"id"`
	// Name must exactly match a registered Tool name
	Name string `json:"name"`
	// Arguments must contain one valid JSON value when present
	Arguments json.RawMessage `json:"arguments,omitempty"`
}

// ToolDefinition describes a Tool to a Provider
type ToolDefinition struct {
	// Name uniquely identifies the Tool within a Runtime
	Name string `json:"name"`
	// Description explains when the Provider should use the Tool
	Description string `json:"description,omitempty"`
	// InputSchema describes Arguments but is not enforced by the minimal Runtime
	InputSchema json.RawMessage `json:"input_schema,omitempty"`
	// Capabilities identifies host permissions required to execute this Tool
	//
	// Capabilities are retained by the host and are not sent to model Providers
	Capabilities []string `json:"-"`
	// ExtensionID identifies the process-isolated Extension that registered this Tool
	//
	// ExtensionID is retained by the host and is not sent to model Providers
	ExtensionID string `json:"-"`
	// ExtensionGeneration identifies the Extension generation pinned to a Run
	//
	// ExtensionGeneration is retained by the host and is not sent to model Providers
	ExtensionGeneration uint64 `json:"-"`
}

// ToolResult records the observable result of one ToolCall
type ToolResult struct {
	// CallID identifies the ToolCall that produced this result
	CallID string `json:"call_id"`
	// Name identifies the Tool that was requested
	Name string `json:"name"`
	// Output contains either Tool output or an error description
	Output string `json:"output,omitempty"`
	// IsError reports whether execution failed without terminating the Run
	IsError bool `json:"is_error,omitempty"`
}

// Tool executes a capability exposed to a Provider
//
// Implementations must be safe for concurrent use when a Runtime is shared by
// multiple callers. Non-context errors are returned to the Provider as a Tool
// result so it can recover
type Tool interface {
	Definition() ToolDefinition
	Execute(ctx context.Context, call ToolCall) (ToolResult, error)
}

// ToolSource acquires one immutable Tool generation for a complete Run
//
// Implementations must be safe for concurrent use. The returned release
// function is called exactly once after the Run terminates, including after
// cancellation. A nil release function is treated as a no-op
type ToolSource interface {
	AcquireTools(ctx context.Context) (tools []Tool, release func(), err error)
}

// HookDefinition describes the Run Events observed by one Hook
type HookDefinition struct {
	// EventTypes lists the exact Event types delivered to the Hook
	EventTypes []EventType
	// ExtensionID identifies the process-isolated Extension that registered this Hook
	ExtensionID string
	// ExtensionGeneration identifies the Extension generation pinned to a Run
	ExtensionGeneration uint64
}

// Hook observes selected Run Events before they are persisted and published
//
// Hooks execute synchronously in registration order and must honor context
// cancellation. Returning an error fails the Run
type Hook interface {
	Definition() HookDefinition
	Handle(ctx context.Context, event Event) error
}

// RunComponents contains one immutable set of Run-scoped Extension components
type RunComponents struct {
	Tools []Tool
	Hooks []Hook
}

// ComponentSource acquires one immutable component generation set for a Run
//
// Implementations must acquire Tools and Hooks atomically so every component
// used by one Run belongs to the same Extension generations. The returned
// release function is called exactly once after the Run terminates
type ComponentSource interface {
	AcquireComponents(ctx context.Context) (components RunComponents, release func(), err error)
}

// RunInfo identifies the Run currently executing a Tool
type RunInfo struct {
	// RunID uniquely identifies the current Run
	RunID string
	// ParentRunID identifies the delegating Run when available
	ParentRunID string
	// AgentID identifies the configured Agent when available
	AgentID string
	// SessionID identifies the logical Session when available
	SessionID string
	// Capabilities contains optional Run-level capability restrictions
	Capabilities []string
}

// ModelRequest contains the context and Tool definitions sent to a Provider
type ModelRequest struct {
	// AgentID identifies the configured Agent when supplied by the caller
	AgentID string `json:"agent_id,omitempty"`
	// SessionID identifies the logical Session when supplied by the caller
	SessionID string `json:"session_id,omitempty"`
	// Metadata contains caller-defined values copied for each Provider call
	Metadata map[string]string `json:"metadata,omitempty"`
	// Instructions contains the system-level instruction for this Run
	Instructions string `json:"instructions,omitempty"`
	// Messages contains the accumulated conversation for this Run
	Messages []Message `json:"messages"`
	// Tools contains the immutable Tool definitions acquired for this Run
	Tools []ToolDefinition `json:"tools,omitempty"`
	// CachePlan contains Provider-neutral routing and breakpoint decisions
	CachePlan *CachePlan `json:"cache_plan,omitempty"`
}

// Provider streams the next assistant Message for an Agent Run
//
// Implementations must honor context cancellation and must be safe for
// concurrent use when a Runtime is shared by multiple callers. Stream must
// eventually emit one completed Message with RoleAssistant or return an error
type Provider interface {
	Name() string
	Stream(ctx context.Context, request ModelRequest) (ModelStream, error)
}

// ModelIDProvider optionally exposes the configured model for request observability
//
// Runtime uses ModelID in Prefix Manifests when a Provider implements this
// interface. It does not affect Provider selection or request routing.
type ModelIDProvider interface {
	ModelID() string
}

// RunRequest describes one Agent Run
type RunRequest struct {
	// AgentID identifies the configured Agent for events and Provider calls
	AgentID string `json:"agent_id,omitempty"`
	// ParentRunID links this Run to the Run that delegated it when available
	ParentRunID string `json:"parent_run_id,omitempty"`
	// SessionID identifies the logical Session without providing persistence
	SessionID string `json:"session_id,omitempty"`
	// Input contains the initial conversation and must not be empty
	Input []Message `json:"input"`
	// Metadata contains caller-defined values passed to the Provider
	Metadata map[string]string `json:"metadata,omitempty"`
	// Instructions contains the system-level instruction passed to each Provider call
	Instructions string `json:"instructions,omitempty"`
	// Budget optionally enforces limits shared with related Runs
	Budget *Budget `json:"-"`
	// Deadline optionally shortens the caller Context deadline
	Deadline time.Time `json:"deadline,omitempty"`
	// Capabilities further restrict the host capabilities available to this Run
	//
	// An empty set leaves Profile-level capability policy unchanged
	Capabilities []string `json:"capabilities,omitempty"`
	// Resume supplies a response for a persisted pending wait instead of adding input
	//
	// SessionID is required and Input must be empty when Resume is set
	Resume *WaitResponse `json:"resume,omitempty"`
}

// RunStatus is the terminal state of a Run
type RunStatus string

// Terminal Run statuses
const (
	RunStatusCompleted RunStatus = "completed"
	RunStatusFailed    RunStatus = "failed"
	RunStatusCanceled  RunStatus = "canceled"
)

// EventType identifies a state change emitted by a Run
type EventType string

// Event types emitted by the minimal runtime
const (
	EventRunStarted       EventType = "run.started"
	EventUserMessageAdded EventType = "user.message.added"
	EventContextCompacted EventType = "context.compacted"
	EventModelRequest     EventType = "model.request.started"
	EventMessageStarted   EventType = "message.started"
	EventMessageDelta     EventType = "message.delta"
	EventMessageCompleted EventType = "message.completed"
	EventToolStarted      EventType = "tool.started"
	EventToolCompleted    EventType = "tool.completed"
	EventRunWaiting       EventType = "run.waiting"
	EventRunResumed       EventType = "run.resumed"
	EventRunCompleted     EventType = "run.completed"
	EventRunFailed        EventType = "run.failed"
	EventRunCanceled      EventType = "run.canceled"
)

// Event is one ordered state change emitted by a Run
type Event struct {
	// Sequence starts at one and increases monotonically within a Run
	Sequence uint64 `json:"sequence"`
	// Type identifies the state transition
	Type EventType `json:"type"`
	// RunID identifies the Run that emitted the Event
	RunID string `json:"run_id"`
	// ParentRunID identifies the delegating Run when this is a child Run
	ParentRunID string `json:"parent_run_id,omitempty"`
	// Time records when the Runtime emitted the Event in UTC
	Time time.Time `json:"time"`
	// SessionRevision is the persisted Event revision when a Session Store is configured
	SessionRevision uint64 `json:"session_revision,omitempty"`
	// AgentID identifies the configured Agent when available
	AgentID string `json:"agent_id,omitempty"`
	// SessionID identifies the persisted Session when available
	SessionID string `json:"session_id,omitempty"`
	// PrefixManifest identifies the content-free Context Segment fingerprints
	// used for a model.request.started Event
	PrefixManifest *PrefixManifest `json:"prefix_manifest,omitempty"`
	// CachePlan describes the effective Provider cache decision for a model request
	CachePlan *CachePlan `json:"cache_plan,omitempty"`
	// ContextCheckpoint is the newly published Checkpoint for context.compacted
	ContextCheckpoint *ContextCheckpoint `json:"context_checkpoint,omitempty"`
	// ContextCompaction describes the provider-neutral reduction for context.compacted
	ContextCompaction *ContextCompactionReport `json:"context_compaction,omitempty"`
	// Message is present for message events
	Message *Message `json:"message,omitempty"`
	// Delta contains incremental assistant text for message.delta
	Delta string `json:"delta,omitempty"`
	// ToolCall is present for Tool events
	ToolCall *ToolCall `json:"tool_call,omitempty"`
	// ToolResult is present when Tool execution completes
	ToolResult *ToolResult `json:"tool_result,omitempty"`
	// WaitRequest describes external input required by run.waiting
	WaitRequest *WaitRequest `json:"wait_request,omitempty"`
	// WaitResponse identifies the request resumed by run.resumed
	WaitResponse *WaitResponse `json:"wait_response,omitempty"`
	// Error contains the terminal error description for failed or canceled Runs
	Error string `json:"error,omitempty"`
}

// RunResult contains the terminal state and accumulated conversation of a Run
type RunResult struct {
	// RunID uniquely identifies the Run within emitted output
	RunID string `json:"run_id"`
	// ParentRunID identifies the delegating Run when this is a child Run
	ParentRunID string `json:"parent_run_id,omitempty"`
	// AgentID is copied from RunRequest
	AgentID string `json:"agent_id,omitempty"`
	// SessionID is copied from RunRequest
	SessionID string `json:"session_id,omitempty"`
	// Status contains the terminal Run state
	Status RunStatus `json:"status"`
	// Messages contains input, assistant, and Tool result messages
	Messages []Message `json:"messages"`
	// ToolResults contains every completed ToolCall in execution order
	ToolResults []ToolResult `json:"tool_results,omitempty"`
	// ProviderCalls reports attempted Provider calls
	ProviderCalls int `json:"provider_calls"`
	// ToolCalls reports attempted Tool calls
	ToolCalls int `json:"tool_calls"`
	// Usage aggregates Provider-reported usage for this Run
	Usage Usage `json:"usage"`
	// Budget reports shared resource consumption when RunRequest supplied one
	Budget *BudgetSnapshot `json:"budget,omitempty"`
	// SessionRevision is the last persisted revision observed by this Run
	SessionRevision uint64 `json:"session_revision,omitempty"`
	// ContextCheckpoint is the latest validated Checkpoint used by this Run
	ContextCheckpoint *ContextCheckpoint `json:"context_checkpoint,omitempty"`
	// ContextCompaction is the latest context reduction published by this Run
	ContextCompaction *ContextCompactionReport `json:"context_compaction,omitempty"`
	// CachePlan is the latest Provider cache decision used by this Run
	CachePlan *CachePlan `json:"cache_plan,omitempty"`
}
